#!/usr/bin/perl -w 

use strict;
use Net::Packet::Dhcpclient;
use Data::Dumper;

my $test=Net::Packet::Dhcpclient->new(State => 'Discover');
print Dumper($test);
print "\n";
#$test->createpacket();
$test->interface('eth0');
#$test->state('Discover');
$test->printpacket();
$test->packetsend();

